# Generated by Django 5.1.5 on 2025-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название главной задачи')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Плановый срок выполнения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
            ],
            options={
                'verbose_name': 'Главная задача',
                'verbose_name_plural': 'Главная задачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('limit_time', models.CharField(max_length=20, verbose_name='Срок выполнения задачи')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('in_progress', 'В процессе выполнения'), ('not_started', 'Не приступал к выполнению')], default='not_started', max_length=20, verbose_name='Статус')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии к задаче')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активности задачи')),
                ('is_important', models.BooleanField(default=False, verbose_name='Признак важности задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
