# Generated by Django 5.1.5 on 2025-01-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parenttask',
            options={'verbose_name': 'Главная задача', 'verbose_name_plural': 'Главные задачи'},
        ),
        migrations.AddField(
            model_name='parenttask',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
