# Generated by Django 5.1.5 on 2025-01-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_parenttask_options_parenttask_end_date'),
        ('users', '0003_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenttask',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tasks', to='users.manager', verbose_name='Менеджер'),
        ),
    ]
