# Generated by Django 5.1.5 on 2025-01-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_parenttask_manager'),
        ('users', '0003_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='users.manager', verbose_name='Создатель задачи'),
        ),
    ]
