# Generated by Django 5.1.5 on 2025-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='parenttask',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'Выполнено'), ('in_progress', 'В процессе выполнения'), ('not_started', 'Не приступал к выполнению')], default='not_started', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
